version: '3'

services:
  web:
    container_name: myriad-web
    image: myriadsocial/myriad-web
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    ports:
      - 3004:3000
    networks:
      myriad:
        ipv4_address: 172.27.4.1
        aliases:
          - myriad-web

networks:
  myriad:
    external: true
