name: CII

on:
  branch_protection_rule:
  schedule:
    - cron: '00 5 * * 0'

permissions:
  contents: read

concurrency:
  group: cii-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'branch_protection_rule' }}

jobs:
  openssf-scorecard:
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    runs-on: ubuntu-20.04
    name: OpenSSF Scorecards
    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Analize
        uses: ossf/scorecard-action@80e868c13c90f172d68d1f4501dee99e2479f7af
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload Result to Artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: Upload Result to Code-Scanning
        uses: github/codeql-action/upload-sarif@83f0fe6c4988d98a455712a27f0255212bba9bd4
        with:
          sarif_file: results.sarif
