name: CII

on:
  branch_protection_rule:
  schedule:
    - cron: '00 5 * * 0'

permissions:
  contents: read

concurrency:
  group: cii-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'branch_protection_rule' }}

jobs:
  openssf-scorecard:
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    runs-on: ubuntu-20.04
    name: OpenSSF Scorecards
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Analize
        uses: ossf/scorecard-action@80e868c13c90f172d68d1f4501dee99e2479f7af
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload Result to Artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: Upload Result to Code-Scanning
        uses: github/codeql-action/upload-sarif@04df1262e6247151b5ac09cd2c303ac36ad3f62b
        with:
          sarif_file: results.sarif
