name: CII

on:
  branch_protection_rule:
  schedule:
    - cron: '00 5 * * 0'

permissions:
  contents: read

concurrency:
  group: cii-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'branch_protection_rule' }}

jobs:
  openssf-scorecard:
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    runs-on: ubuntu-20.04
    name: OpenSSF Scorecards
    steps:
      - name: Checkout Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Analize
        uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload Result to Artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: Upload Result to Code-Scanning
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a
        with:
          sarif_file: results.sarif
