name: SAST

on:
  pull_request:
  schedule:
    - cron: '00 5 * * 0'

permissions:
  contents: read

concurrency:
  group: sast-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript
          - typescript
    runs-on: ubuntu-20.04
    name: CodeQL ( ${{ matrix.language }} )
    steps:
      - name: Checkout Repository
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247
      - name: Initialize
        uses: github/codeql-action/init@d186a2a36cc67bfa1b860e6170d37fb9634742c7
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@d186a2a36cc67bfa1b860e6170d37fb9634742c7
      - name: Analize
        uses: github/codeql-action/analyze@d186a2a36cc67bfa1b860e6170d37fb9634742c7
